on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, edited, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created, edited]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: abeyuya/actions-mention-to-slack@v2
        with:
          repo-token: "5dae456b98c9cfc7d82647ce5d1242d6b9d33d50"
          slack-webhook-url: "https://hooks.slack.com/services/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"
          icon-url: https://img.icons8.com/color/256/000000/github-2.png
          bot-name: "GitHubメンション通知Bot"
